export const TOMATOX_THEME = {
    THEME_COLOR: '#ff5c49',
    BACKGROUND_COLOR: '#2b2b2b',
    HIGHLIGTH_BACKGROUND_COLOR: '#3d3d3d',
    FONT_COLOR: '#f1f1f1',
    UNIMPORTANT_FONT_COLOR: '#bbbbbb',
    DISABLED_FONT_COLOR: '#a1a1a1',
    COMPONENT_DARK_BACKGROUND: 'rgba(0,0,0,0.2)',
    COMPONENT_LIGHT_BACKGROUND: 'rgba(111,111,111,0.1)',
    SPLIT_LINE_COLOR: '#474747'
}
